version: 1.0.{build}

# TODO: Support Visual Studio 2017
image: Visual Studio 2019

platform: x64

branches:
  except:
    - /main-new-.*/
    - /ghactionsonly-.*/

environment:
  matrix:
    - COMPILER: cygwin
      OQS_ALGS_ENABLED: STD
# To be supported later
#    - BUILD_SHARED: OFF
#      COMPILER: msvc2019
#      OQS_ALGS_ENABLED: NIST_R4
#    - BUILD_SHARED: OFF
#      COMPILER: msvc2019
#      OQS_USE_OPENSSL: ON
#      OQS_ALGS_ENABLED: All
#    - BUILD_SHARED: ON
#      COMPILER: msvc2019
#    - BUILD_SHARED: OFF
#      COMPILER: msys2
#    - BUILD_SHARED: ON
#      COMPILER: msys2

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor_build.bat'

test_script:
  - cmd: |-
         cd %APPVEYOR_BUILD_FOLDER%
         c:\cygwin64\bin\bash.exe -lc "./scripts/runtests.sh -V"

